### ISSUE TITLE
Clean package install will fail on examples/simple.py - missing positional argument 'model'

### ISSUE THREAD

**Issue by sjoerdk** [felix-martel/pydanclick#15]
Thanks for starting this package! Seems very useful.
I ran into an issue that I just wasn't able to debug fully. Do you have any idea?

**To reproduce**
* create a clean python 3.9 or 3.10 env called 'cause_issue'
* activate the env
* Then just install and run the basic example example/simple.py
```
$ pip freeze                                       # no output as this is a clean env
$ python --version
Python 3.9.19                                    
$ pip install pydanclick
Collecting pydanclick
...
Installing collected packages: typing-extensions, click, annotated-types, pydantic-core, pydantic, pydanclick
Successfully installed annotated-types-0.6.0 click-8.1.7 pydanclick-0.2.0 pydantic-2.8.0 pydantic-core-2.20.0 typing-extensions-4.12.2
$ python examples/simple.py
Traceback (most recent call last):
  File "~/examples/simple.py", line 23, in <module>
    @from_pydantic(TrainingConfig)
TypeError: from_pydantic() missing 1 required positional argument: 'model
```

**Workaround**
You can work around this issue by explicitly passing the required arguments in the function decorator:
```
@from_pydantic(__var='training_config', model=TrainingConfig)

instead of the original

@from_pydantic(TrainingConfig)
```

**What I tried**
Tried clean envs in both poetry and outside poetry (using conda) for both python 3.9 and 3.10
I cloned the the pydanclick repo and ran `poetry install`. The issue does then **not** come up. Something in the pydanclick poetry.lock file seems to avoid the issue. However the pyproject.toml dependencies do not.

I tried to install every package mentioned in pydanclick poetry.lock individually to see whether any package affects the python interpretation of `@from_pydantic` without success. The issue is still there after installing all.

**Comment by felix-martel** [comment]
Hello, thanks for the thorough bug report! It should be fixed with version `0.2.1`. 

(Changes from #12 had not been published to PyPI, thanks for reporting)
