### ISSUE TITLE
Rename the model arguments

### ISSUE THREAD

**Issue by azmeuk** [felix-martel/pydanclick#18]
It would be useful to be able to choose a different name for the click command pydantic argument:

```python
from pydanclick import from_pydantic

@click.command()
@from_pydantic(TrainingConfig)
def cli(obj: TrainingConfig):
    ...
```
Currently this code generate an exception:

```python
TypeError: cli() got an unexpected keyword argument 'training_config'
```

This would help with dynamically generated commands, in the form of:

```python
from pydanclick import from_pydantic
...
models = [Foo, Bar, Baz]

for Model in models:
    @click.command()
    @from_pydantic(Model)
    def cli(obj: Model):
        ...
```

What do you think?

**Comment by felix-martel** [comment]
If I understand your request correctly, that can be achieved with:

```python
from pydanclick import from_pydantic

@click.command()
@from_pydantic("obj", TrainingConfig)
def cli(obj: TrainingConfig):
    ...
```

(I agree it's [buried](https://felix-martel.github.io/pydanclick/#add-regular-options-and-arguments) deep in the documentation, I should make it more explicit)

**Comment by azmeuk** [comment]
Yes, this is what I was looking for.
Thank you!
