### ISSUE TITLE
Project general philosophy and strategy for contributors

### ISSUE THREAD

**Issue by noirbizarre** [felix-martel/pydanclick#28]
Hi 👋🏼 

First, I'd like t say it's a very interesting project ! I just started using it, I see a lot of potential and given I intend to contribute, I have some questions I'd like to ask about the general direction of this project.

## Pull-request or issue first

Are you open to people submitting a candidate pull request on some ideas they have without going through an issue first ?
I know some projects refuse pull requests if they have not been discussed first in an issue. This is something I can totally understand, but this also force a very slow contribution rhythm.

So is it acceptable to you to have some incoming pull-requests and iterate in the PR discussion if necessary instead of an issue ?

(In the meantime, I will open issues to start discussing the 2 first use-case I'd like to contribute)

## Philosophy

I started digging a bit the code base and I reach a question: is this project intend to be:
1. click+click-ecosystem first: types and features needs to match some existing click or click ecosystem. Ex: if I want to add support for a type, it needs to match an existing extension like one of https://github.com/click-contrib/click_params
2. pure click first: types and features needs to match an existing click API or mechanism first and so prioritize [this kind of approach](https://github.com/felix-martel/pydanclick/blob/main/pydanclick/model/type_conversion.py#L109-L130) (aka. translate Pydantic mechanism into click mechanism reusing click API as much as possible)
3. Pydantic first: the goal is to support as much Pydantic feature as possible, and so delegating some logic which is initial `click` responsibility to `pydantic` is acceptable. As a consequence, providing a reusable field type relying on [this](https://github.com/pydantic/pydantic/discussions/7367#discussioncomment-6953794), is acceptable

**Comment by felix-martel** [comment]
Hello, thanks for your interest in the project!

Regarding PRs: I'm perfectly fine with accepting them without creating issues beforehand. The two issues you opened seems perfectly reasonable to me.

Philosophy: I'm leaning towards Pydantic-first. IMO using native Click features creates nicer integration (error messages, documentation, that stuff), but when it's not possible then I'm okay relying on Pydantic features. That's what we're doing for validation already: as long as the type has no native type support, we rely on Pydantic parsing logic. Not sure what you mean by "a resuable field type" though.

**Comment by noirbizarre** [comment]
Thanks for your answers !

For PRs, I submit the first ones 👍🏼 
For the philosophy, it's clear, I am totally aligned 👌🏼 That will help me on the network types because this was mostly for this one that I was wondering.
